### ISSUE TITLE
mex -setup build error 

### ISSUE THREAD

**Issue by phongnhhn92** [devkicks/ParticleFilterMatlab#1]
Hello, i tried to run mexme_pf_color_tracker.m but I failed to build pdfcolor_ellipserand.c. I already try to do mex -setup with MS VS 2015 installed in my computer but so far I have error. Could you provide me the link to down down the C compiler you used for this project ? 
![capture](https://cloud.githubusercontent.com/assets/11288381/20877321/3648a424-bb0b-11e6-91c7-e70125239256.PNG)

**Comment by masadcv** [comment]
Hi,
Can you show output of mex -setup as well?

I am using the following compiler:
```
>> mex -setup
MEX configured to use 'Microsoft Visual C++ 2010 (C)' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. In the near future
	 you will be required to update your code to utilize the
	 new API. You can find more information about this at:
	 http://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN
```

**Comment by masadcv** [comment]
Also this code is a backup of the following original code: [https://uk.mathworks.com/matlabcentral/fileexchange/17960-particle-filter-color-tracker](Particle Filter Color Tracker Matlab)

Please refer to the comments on this page to solve your issue.
